### ISSUE TITLE
SMPT_SECURITY is invalid. Example .env and config.json needs updating

### ISSUE THREAD

**Issue by F1zzyD** [vineethmn/vaultwarden-docker-compose#3]
After filling out the necessary fields in the .env and config.json files for docker compose, users will get the error: ``SMTP_SECURITY` is invalid. It needs to be one of the following options: starttls, force_tls or off`

On top of that, this docker compose version fails to establish a log in for vaultwarden. I'm assuming it's just outdated, but it is useless in this state.

**Comment by vineethmn** [comment]
I believe `SMTP_SECURITY` is not included in `.env` and `config.json`. I don't this is a mandatory environment. Are you getting this invalid error even if the variable is not configured? if that so, I will amend the same.

Regarding `docker-compose` version, I will update the same.
