### ISSUE TITLE
Allow Signup when set in .env

### ISSUE THREAD

**Issue by karladler** [vineethmn/vaultwarden-docker-compose#5]
https://github.com/vineethmn/vaultwarden-docker-compose/blob/f8e7fdbf637f30e9e487ff231faa9b669ebf2bb7/docker-compose.yml#L15C6-L15C29

I think this should take the environment variable instead of overwriting it hardcoded to `false`

**Comment by vineethmn** [comment]
This setting was enforced to avoid any unauthorized signups. I have added note in instruction (Readme) to set this to `true` for initial setup.
